my_name=str("emobilis")
my_number=int(564)
my_number2=float(45.6)
my_bool=bool(True)
my_bool1=bool(False)
my_complex=complex(1j)
print(my_name)
print(my_number)
print(my_number2)
print(my_bool)
print(my_bool1)
print(my_complex)

